# Generated by Django 3.1.2 on 2020-10-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
    ]
