# Generated by Django 3.1.2 on 2020-10-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subject_posts_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_c', to='app.subject'),
        ),
    ]
