# Generated by Django 3.1.2 on 2020-10-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201019_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='posts_count',
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
