# Generated by Django 3.1.2 on 2020-10-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='session',
            field=models.CharField(choices=[('فصل أول', 1), ('فصل ثاني', 2)], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
