# Generated by Django 3.1.2 on 2020-10-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201020_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='session',
            field=models.CharField(choices=[('1', 'فصل أول'), ('2', 'فصل ثاني')], max_length=15),
        ),
    ]
