# Generated by Django 3.1.2 on 2020-10-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('1', 'محاضرة'), ('2', 'تسجيل'), ('3', 'تفريغ')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subject_type',
            field=models.CharField(choices=[('1', 'نظري'), ('2', 'عملي')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
