# Generated by Django 3.1.2 on 2020-10-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201020_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('محاضرة', 'محاضرة'), ('تسجيل', 'تسجيل'), ('تفريغ', 'تفريغ')], max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject_type',
            field=models.CharField(choices=[('نظري', 'نظري'), ('عملي', 'عملي')], max_length=15),
        ),
    ]
