# Generated by Django 3.1.2 on 2020-10-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='content',
            field=models.TextField(),
        ),
    ]
