# Generated by Django 3.1.2 on 2020-10-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201029_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='year',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=20, null=True),
        ),
    ]
