# Generated by Django 3.1.2 on 2020-11-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201030_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='session_year',
        ),
        migrations.DeleteModel(
            name='SessionYear',
        ),
    ]
